### PR TITLE
Added eslint-plugin-fliplet

### PR DESCRIPTION
**Pull request by squallstar**
I have added the eslint package that we require to integrate with Codacy to analyze our open-source repositories at https://github.com/Fliplet. 

See attached error for ESLint on Codacy:
image

### CODE REVIEW

**Review by lolgab — APPROVED** [review]

**Comment by lolgab** [comment]
Thank you for your contribution!

**Comment by lolgab** [comment]
This plugin is now available on codacy.com
You can now re-run your analysis.

**Comment by squallstar** [comment]
Awesome, thanks for the update @lolgab!

**Comment by squallstar** [comment]
@lolgab I just tried now and I got the following error despite having a valid `package.json` file:

```
JSON :
Error on file package.json:1. Cause: Parsing error: Unexpected token :
```

image

- This is the sample PR being tested: https://github.com/Fliplet/fliplet-widget-form-builder/pull/342
- Here is on Codacy: https://app.codacy.com/gh/Fliplet/fliplet-widget-form-builder/commit?cid=508116710&fileBranchId=20871030
- This is the package.json file https://github.com/Fliplet/fliplet-widget-form-builder/blob/33117e2ebf271f50975fddebf03120694cbc3da9/package.json

**Comment by lolgab** [comment]
The ones you see here are mostly warnings caused by a bad behaving plugin.
We're going to fix the json related problem but you can safely ignore it for now.
I triggered a re-run and I can see correctly issues from ESLint on your repository.

**Comment by squallstar** [comment]
@lolgab doesn't look like it's working for me.

1. PR overview shows no issue and up to standards
image

2. Build Logs don't even show ESLint 
image

3. If I click on the latest commit, it shows all items have passed while ESLint should have failed
image

4. GitHub shows Codacy tests have passed for the PR https://github.com/Fliplet/fliplet-widget-form-builder/pull/342
image

If I run ESLint locally it's correctly failing as per invalid code I have put in the PR (https://github.com/Fliplet/fliplet-widget-form-builder/pull/342/files#diff-52ce1f1d107f4820ceccc3ae970c10f2671f7a66fcf9e571891ee27d89b50f3dR108)

**Comment by squallstar** [comment]
@lolgab any update on this? Sorry I'm just making sure this doesn't get lost as I am keen to test out this integration to then speak with my managers in regards to buying a premium plan if Codacy turns out to be a good tool.

**Comment by squallstar** [comment]
@lolgab sorry to bother but is there any update on this?

**Comment by lolgab** [comment]
Sorry, didn't notice your previous message. Let me check what's going on.

**Comment by lolgab** [comment]
Hi @squallstar,
The problem seems to be that the file `js/libs/builders.js` has a fatal error ( flagged in Codacy as "Error in file" ).
Codacy blocks a PR only if it finds issues. When the tools fails to analyse a file, like in this case with `js/libs/builders.js`, we assume it's a problem in a tool of ours and we skip that file when we have to decide to block a PR or not.
If you commit a `js` file with no syntax errors ( the ones that make ESLint fail ) and with normal issues, you should be able to see the issues and to have red status on the PR.
I noticed that you have the old `Codacy/PR Quality Review` required on Github. Since we moved to Github checks, this step is not used anymore, I suggest you to remove it from the Github Branch settings page.

**Comment by squallstar** [comment]
@lolgab sorry but that seems ridiculous, you are telling me that if a file has a syntax error it cannot be picked up and flag the PR accordingly? What is the whole point of having the Codacy integration on GitHub to avoid merging code that doesn't adhere to the standards if it doesn't work like ESLint does? To confirm, ESLint can correctly parse the file and flag the syntax error on all my environments.

If you don't provide this basic functionality I'm afraid we'll have to switch provider as it doesn't meet our most basic needs.

**Comment by lolgab** [comment]
I'm sorry that this disappoints your expectations.
Sadly tools are not perfect and, when they work as expected, we have to deal with the model we use to represent issues, based on patterns with specific id, etc.
We could consider tools fatal errors issues that block pull requests, but this would break a lot of use cases when some other tools are failing on some files not because of actual errors, but because of tools limitations.
We could consider fatal errors in ESLint non fatal ones, but they miss the pattern and the line number (we should file the issues on line 1) information. Moreover, ESLint has problems parsing certain files ( JSON for example ) and making fatal errors issues would make it impossible for a lot user to marge correct pull requests.
This is not perfect, but it is a tradeoff based on the various limitations of ours and of the various tools we support.
There is a basic assumption behind this, Codacy is a code quality tool, we try to enforce quality assuming that the code, at least, compiles. Of course on a JIT compiled language as Javascript you can't compile the code ahead of time, but we assume that you have a basic test suite on your project that would give a red already on CI before even thinking about code quality.
Sadly, we can't change this behaviour because it will break too many use cases.
I hope this answer, if it doesn't convince you, as least lets you understand the reasons behind this behaviour.

**Comment by squallstar** [comment]
@lolgab thanks for such explanation, I appreciate the time you spent into detailing the issue and limitations.

I will be looking into what alternatives we have to simply have a CI step to attempt at compiling the files. I thought Codacy could take care of this so I don't need to set up a specific CI integration but this unfortunately doesn't seem to be the case.

Once again I appreciate the help you've given so far, many thanks.

**Pull request merged**
