### PR TITLE
Add `eslint-plugin-regexp` and update documentation

### PR DESCRIPTION
**Pull request by cobaltt7**
This plugin finds errors, unneeded characters, and etcetera in regular expressions.

### CODE REVIEW

**Comment by cobaltt7** [comment]
It seems like `npm run generateDocs` generated docs for `eslint-plugin-regexp` **and** updated all the other documentation files. Sorry about that, as it's unrelated!

**Comment by lolgab** [comment]
Hi @RedGuy12,
Thank you very much for this contribution.

> It seems like `npm run generateDocs` generated docs for `eslint-plugin-regexp` **and** updated all the other documentation files. Sorry about that, as it's unrelated!

Nothing to be sorry about, it is a problem we have with PRs by Dependabot, which doesn't run `generateDocs` and so leaves outdated files in the repository.

You need to rebase on top of current master since, the `package-lock.json` has conflicts.
Once you do I'm happy to merge it!

**Comment by cobaltt7** [comment]
Ok, will do.

Maybe to fix that problem, you could make a workflow that runs `npm run generateDocs` on PRs?
________________________________

**Comment by lolgab** [comment]
> Maybe to fix that problem, you could make a workflow that runs `npm run generateDocs` on PRs?

We already have it as a pre-commit hook but dependabot skips them entirely.
`npm run generateDocs` already runs on PRs but the changes are only reflected in the generated docker image, not back to the repository itself.

**Comment by cobaltt7** [comment]
i don't know why it closed itself

**Comment by cobaltt7** [comment]
There we go!

@lolgab, I have resolved the conflicts. Please merge

**Pull request closed without merging**
